name: First Workflow
on: workflow_dispatch
jobs: 
 first-job:
  runs-on: macos-12
  steps: 
    - name: Print greeting
      run: |
       echo "First output"
       echo "Second output"       
    - name: Print goodbye
      run: echo "Done -bype!"
